### ISSUE TITLE
Soviet annex builds ruin the game

### ISSUE THREAD

**Issue by Juddur** [scuffed56/SCUFFED5.0#18]
Get rid of eastern allies focus, replace it with temporary buff instead of a focus that adds 16 building slots and 16 civs on top of already released puppets

**Comment by Fullchord** [comment]
Replace it with 5% consumer goods, 10% construction speed, and 10% fact output would align with the point of the focus rather than pointlessly spawning in civs for annex build. The difference between sov players who have allies who release puppets and those who do not is like night and day, which should not be the point. I plan on removing EVERY sov releasable but have a focus that gives all the cores back when the ALT hist path is completed, so the civil war works. This will allow us to balance the country off of itself rather than off of dumb replaceable nations in general.

**Comment by atomicplan666** [comment]
Fixed with the removal of puppets
