### ISSUE TITLE
Keeping factory bloat down/concentrated industry?

### ISSUE THREAD

**Issue by Juddur** [scuffed56/SCUFFED5.0#19]
I think there is too much factory bloat currently especially with new change of focus times(which should be done) and the nat ideas now giving what their original buffs did. Current ways of combating this in my opinion would be
1) Nerfing minimum training time(making encirclements matter a heck of a lot more)
2) Nerfing Base Factory output in defines(maybe?)-last resort tbh
3) Nerfing Nat ideas back down to its previous values
4) Changing some defines for factory retention and base values and or making each industry type have more meaning for example
4.a)Dispersed give more retention bonuses however less factory output(may not be necessary depending on how Conc. is handled)
4.b)Concentrated should be a niche, and if done correctly should give more output when used correctly, In my opinion increase factory output modifiers by 1.5x and add some retention/base nerfs along with a factory bomb vulnerability debuff
My logic is that Concentrated should only be for nations who have all three
A-Cannot be bombed
B-Has limited research capabilities
C-only produces 1 type of army equipment ie.tanks and just tanks(and out of date ones for the most part)

**Comment by Fullchord** [comment]
I think we should nerf nat ideas back down and find some defines for training time ASAP (mby removing training speed from peacetime??). But as a whole, I think there could be some really interesting ideas we could do to make industry tech more interesting. As a thought, we could fully rework how concentrated work is and have both of them split (like tools do) to allow the player more choice in their path and how they like to play their countries. For example, one could give less output but a higher cap, etc. Just an idea for the future as we branch further away from vanilla/56.

**Comment by xfrenzzyy** [comment]
I do think concentrated needs buffed because there is a big difference between dispersed and concentrated, just not sure how to do that without making dispersed obsolete.  The training time I don't really care which way it goes, I do think most of these points are made based off of 2x games which shouldn't be taken seriously at all. Also, what National ideas you talking about, the cogwheel, or the one in your government bullshit? If you are talking about the cogwheel, they are pretty new but I think that they are actually pretty balanced. If you talking about the government bullshit, didn't we only remove the pp cost from them? Im not sure what else we did to them.
